"""empty message

Revision ID: 2fe809208503
Revises: 015d0f979286
Create Date: 2025-03-01 09:56:55.093084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe809208503'
down_revision: Union[str, None] = '015d0f979286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chats_name'), 'chats', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_name'), table_name='chats')
    # ### end Alembic commands ###
